services:
  mysql-db:
    image: mysql:9
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    # volumes:
      # - mysql-data:/var/lib/mysql
    networks:
      - db-network

  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: mypgdb
    ports:
      - "5432:5432"
    # volumes:
      # - postgres-data:/var/lib/postgresql/data
    networks:
      - db-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    networks:
      - db-network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: frontend

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    depends_on:
    - mysql-db
    - postgres-db

networks:
  db-network:
    driver: bridge